<?php
include ROOT_PATH.ViewDirectoryName.'/head.phtml';
?>
    <script type="text/javascript" src="/public/js/searchCommon.js"></script>
<center><h1> Library Management System </h1></center>
<center><p>Any user can register an account by providing us your details and then user will be able to login to search for books. </p></center>
<section>
    <form method="get" action="/user/search/search" onsubmit="return checkSearch();">
        <input type="text" name="search" id="search"/>
        <input type="submit" name="submit" value="Search"/>
    </form>
</section >


<?php
include ROOT_PATH.ViewDirectoryName.'/foot.phtml';
?>