<?php
include ROOT_PATH.ViewDirectoryName.'/head.phtml';
?>
<script type="text/javascript" src="/public/js/jquery-3.4.0.min.js"></script>
<script type="text/javascript" src="/public/js/loginCommon.js"></script>

<form action="/user/user/doLogin" method="post" onsubmit="return checkLoginForm();">
    <fieldset class='login_form'>
        <div class="row">
            <label class="fixewidth">Username:</label>
            <input type="text" name="username" required id="username" />
        </div>
        <div class ="row">
            <label class="fixedwidth">Password:</label>
            <input type="password" name="password" required id="password"/>
        </div>
        <input type="hidden" name="token" value="<?php echo $token; ?>">
        <div class="row">
            <input type="submit" name="submit" value="LogIn" id="submit"/>
        </div>
    </fieldset>
</form>



<?php
include ROOT_PATH.ViewDirectoryName.'/foot.phtml';
?>
